# Generated by Django 5.0.3 on 2024-03-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': ('Позвонить',),
                'verbose_name_plural': 'Позвонить',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titel', models.CharField(max_length=120, null=True)),
            ],
            options={
                'verbose_name': ('Прочие услуги',),
                'verbose_name_plural': 'Прочие услуги',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('article', models.TextField(verbose_name='Текст')),
                ('etap', models.TextField(verbose_name='Этапы работ')),
            ],
            options={
                'verbose_name': ('Вид ремонта',),
                'verbose_name_plural': 'Виды ремонта',
            },
        ),
    ]
