# Generated by Django 5.0.3 on 2024-03-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alev', '0002_other_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': ('Прочие услуги',),
                'verbose_name_plural': 'Прочие услуги',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='object')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alev.objects')),
            ],
        ),
    ]
